name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Create ZIP file
        shell: bash
        run: zip -r vatis-profiles-${{ steps.get_version.outputs.version-without-v }}.zip *.json

      - name: Create release note
        shell: bash
        run: |
          cat > CHANGELOG.txt << EOF
          [Download Profiles](https://github.com/vaccfr/vatis-profiles/releases/download/${{ steps.get_version.outputs.version }}/vatis-profiles-${{ steps.get_version.outputs.version-without-v }}.zip)
          ---
          EOF

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          name: vATIS Profiles ${{ steps.get_version.outputs.version-without-v }}
          prerelease: false
          draft: true
          body_path: CHANGELOG.txt
          files: |
            vatis-profiles-${{ steps.get_version.outputs.version-without-v }}.zip
