name: Validate JSON

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.json'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.json'

jobs:
  validtate_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate JSON files
        id: get_version
        uses: GrantBirki/json-yaml-validate@v3
